### ISSUE TITLE
Invalid Key error

### ISSUE THREAD

**Issue by marcosgabbardo** [johnbalvin/pybnb#1]
{"errors":[{"message":"Response not successful: Received status code 400","locations":[{"line":1,"column":1}],"path":[],"extensions":{"response":{"statusCode":400,"body":{"error_code":400,"error":"invalid_key","error_message":"Invalid API key."}},"code":"Bad Request"}}],"data":null}

**Comment by johnbalvin** [comment]
could you show me a minimum reproducible example?
