### ISSUE TITLE
Error when using proxy

### ISSUE THREAD

**Issue by sbaginski** [johnbalvin/pybnb#6]
When a non-empty proxy URL is passed to the function `Get_from_room_id`, the following error occurs:
```
module 'curl_cffi.requests' has no attribute 'utils'
```
I have checked the curl_cffi repository, and it seems that indeed there is no attribute `utils`. Perhaps it was removed in some of the recent updates.

**Comment by johnbalvin** [comment]
my bad, I found the issue, it will be fixed this weekend

**Comment by johnbalvin** [comment]
it should be fixed now, try it
